### PR TITLE
Add customization of placeholder line;

### PR DESCRIPTION
**Pull request by Antondomashnev**
Hi @dblock this PR addresses the #11 issue. I've started with configuration object which could eventually help to resolve multiple issues easier. Let me know what you think about implementation.

### CODE REVIEW

**Comment by dblock** [comment]
I like where it's going, but maybe it's overly complicated? 

Is there any way to have more than one of these configurations? I don't think so, so I would just create a global configuration object ala https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/config.rb and call it a day. Then we can do `DangerChangelog.configure do |config|`. This would avoid passing it around as parameters to start.

**Comment by Antondomashnev** [comment]
@dblock was one of the ideas as well, I think you're right would be clearer and we don't need multiple configurations. I'll update the PR with that approach.

**Comment by Antondomashnev** [comment]
@dblock check out the updated PR, it looks much better now, thanks for your suggestion - every day we learn 😄

**Comment by Antondomashnev** [comment]
@dblock the Travis CI is failing and it seems because of the rubocop's new version. Is there a reason to keep the `Gemfile.lock` in gitignore?

**Comment by dblock** [comment]
Since Gemfile.lock isn't committed rubocop should be locked at a specific version. I usually run `rubocop -a ; rubocop --auto-gen-config`.

**Comment by dblock** [comment]
Perfect, merging.

**Pull request merged**
