### PR TITLE
Accept UTC Formatted Dates

### PR DESCRIPTION
**Pull request by Blackjacx**
###Changes

Adding UTC formatted date with `Z` in the end to the tests

### CODE REVIEW

**Comment by dblock** [comment]
Thanks. Try fixing it!

**Comment by mathroule** [comment]
Supporting datetime in ISO format would be even better: `2023-09-28T21:59:56Z`.

**Comment by mathroule** [comment]
See https://github.com/dblock/danger-changelog/pull/61

**Comment by Blackjacx** [comment]
Nice thanks for this fix 👍

**Pull request closed without merging**
