### PR TITLE
Add support for ISO date & time

### PR DESCRIPTION
**Pull request by mathroule**
# Changes

- Add support for ISO date & time.
- Fixes https://github.com/dblock/danger-changelog/pull/60

# Example
- `2023-09-28`
- `2023-09-28Z`
- `2023-09-28T21:59:56Z`

### CODE REVIEW

**Comment by dblock** [comment]
Great! We need to re-enable CI in this project since Travis CI is MIA. Care to do it? Separate PR probably best. You can use a token for Danger from something like https://github.com/dblock/ruby-enum.

**Comment by mathroule** [comment]
> Great! We need to re-enable CI in this project since Travis CI is MIA. Care to do it? Separate PR probably best. You can use a token for Danger from something like https://github.com/dblock/ruby-enum.

Done in https://github.com/dblock/danger-changelog/pull/62

**Comment by mathroule** [comment]
@dblock the branch is up to date with the new CI checks. Do you mind reviewing the PR? Thanks

**Comment by dblock** [comment]
Merged, thank you! 

Any interest in co-maintaining danger-changelog? Maybe make a release with this change? If yes drop me a note to dblock at dblock dot org with your rubygems username.

**Comment by mathroule** [comment]
Yes, I would be happy to get a new release of danger-changelog. Thanks

My RubyGems username is https://rubygems.org/profiles/mathroule.

**Comment by dblock** [comment]
Added you here and Rubygems @mathroule, accept the GitHub invite here: https://github.com/dblock/danger-changelog/invitations

Please follow https://github.com/dblock/danger-changelog/blob/master/RELEASING.md for a release. Let's first increment the version to 0.7.0 since this was a new feature, too? https://github.com/dblock/danger-changelog/blob/master/lib/changelog/gem_version.rb#L2

**Comment by mathroule** [comment]
Thanks for adding me @dblock. I released version 0.7.0 on RubyGems: https://rubygems.org/gems/danger-changelog.
I also updated GitHub releases: https://github.com/dblock/danger-changelog/releases.

**Pull request merged**
