### PR TITLE
Add support for the Keep a Changelog format

### LINKED ISSUE #7: Map to http://keepachangelog.com
Seems like a thorough set of rules!

http://keepachangelog.com/en/0.3.0/

@olivierlacan

### PR DESCRIPTION
**Pull request by michaelherold**
This PR does a bit of refactoring to the internals of the plugin to make the format detection a little more extensible. It's somewhat clumsy right now but gets the job done for this purpose.

With this new extensibility, I added support for checking for the [Keep a Changelog](https://keepachangelog.com) format. This format checker cannot currently be combined with the Intridea style, but that would be a nice addition.

Closes #7
Closes olivierlacan/keep-a-changelog#125

### CODE REVIEW

**Comment by dblock** [comment]
👏

**Comment by dblock** [comment]
@michaelherold want to help out with co-maintenance? What's your rubygems email again?

**Comment by michaelherold** [comment]
Sure! opensource@michaeljherold.com

**Comment by dblock** [comment]
You're in! https://github.com/dblock/danger-changelog/invitations

**Pull request merged**
